-- 0000-baseline: prod schema 基线(P2-18,v0.2 升级计划)
--
-- 生成方式:2026-06-11 经 Supabase MCP 从 prod(ai-interactive-story, ap-southeast-1)
-- pg_catalog/pg_indexes/pg_constraint 实查汇编(等价 pg_dump --schema-only 的可重建子集)。
-- 用途:① 在空库完整重建 prod schema;② 作为此后一切 DDL 的对照基线。
-- ⚠ 本文件描述的是「批次 4 迁移之前」的 prod 状态;批次 4 起的增量见同目录后续迁移文件。
-- ⚠ 此后 prod 的一切 DDL 一律走 supabase MCP apply_migration(自带台账),不再手敲。
-- prod 已有迁移台账(supabase_migrations):phase1_accounts / drop_global_unique_cards_presets /
--   enable_rls_all_public_tables / phase0_cost_guard_tables / phase0_align_with_repo_migration。

create extension if not exists vector;

-- ── 账户 ──────────────────────────────────────────────────────────────
create table if not exists users (
  id                uuid        not null default gen_random_uuid() primary key,
  username          text        unique,
  email             text        not null unique,
  password_hash     text        not null,
  display_name      text,
  role              text        not null default 'user',
  email_verified_at timestamptz,
  status            text        not null default 'active',
  created_at        timestamptz not null default now(),
  last_seen_at      timestamptz,
  avatar            text
);

create table if not exists auth_tokens (
  token_hash   text        not null primary key,
  user_id      uuid        not null references users(id) on delete cascade,
  created_at   timestamptz not null default now(),
  expires_at   timestamptz not null,
  last_used_at timestamptz,
  revoked_at   timestamptz
);
create index if not exists idx_auth_tokens_user on auth_tokens (user_id);

create table if not exists email_otp (
  id          bigint      generated by default as identity primary key,
  email       text        not null,
  code_hash   text        not null,
  purpose     text        not null default 'register',
  expires_at  timestamptz not null,
  attempts    integer     not null default 0,
  consumed_at timestamptz,
  created_at  timestamptz not null default now()
);
create index if not exists idx_email_otp_lookup on email_otp (email, purpose, created_at desc);

-- ── 会话与消息 ─────────────────────────────────────────────────────────
create table if not exists sessions (
  id         text        not null primary key,
  data       jsonb       not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  user_id    uuid
);
create index if not exists idx_sessions_user on sessions (user_id);

create table if not exists messages (
  session_id text    not null references sessions(id) on delete cascade,
  seq        integer not null,
  data       jsonb   not null,
  primary key (session_id, seq)
);

-- ── 卡库与预设(基线时无 PK;部分唯一索引区分官方/用户行)─────────────────
create table if not exists cards (
  kind       text        not null,
  name       text        not null,
  data       jsonb       not null,
  updated_at timestamptz not null default now(),
  user_id    uuid
);
create index if not exists cards_kind_idx on cards (kind);
create unique index if not exists uq_cards_official on cards (kind, name) where (user_id is null);
create unique index if not exists uq_cards_user on cards (user_id, kind, name) where (user_id is not null);

create table if not exists presets (
  name       text        not null,
  data       jsonb       not null,
  updated_at timestamptz not null default now(),
  user_id    uuid
);
create unique index if not exists uq_presets_official on presets (name) where (user_id is null);
create unique index if not exists uq_presets_user on presets (user_id, name) where (user_id is not null);

-- ── 向量记忆 ───────────────────────────────────────────────────────────
create table if not exists memory_vec (
  session_id text        not null,
  scope      text        not null,
  ext_id     text        not null,
  content    text        not null,
  embedding  vector(512),
  meta       jsonb       not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  user_id    uuid,
  primary key (session_id, scope, ext_id)
);
create index if not exists memory_vec_hnsw on memory_vec using hnsw (embedding vector_cosine_ops);

-- ── phase0 成本熔断 ────────────────────────────────────────────────────
create table if not exists rate_limits (
  key          text        primary key,
  count        integer     not null default 0,
  window_start timestamptz not null default now()
);

create table if not exists usage_daily (
  subject    text          not null,
  day        date          not null,
  turns      integer       not null default 0,
  tokens     bigint        not null default 0,
  usd        numeric(12,6) not null default 0,
  updated_at timestamptz   not null default now(),
  primary key (subject, day)
);
create index if not exists idx_usage_daily_day on usage_daily (day, usd desc);

create table if not exists spend_daily (
  day     date          primary key,
  usd     numeric(12,6) not null default 0,
  tripped boolean       not null default false
);

-- ── RLS:全表开启,不建 policy = Data API 的 anon/authenticated 全拒 ──────
alter table users        enable row level security;
alter table auth_tokens  enable row level security;
alter table email_otp    enable row level security;
alter table sessions     enable row level security;
alter table messages     enable row level security;
alter table cards        enable row level security;
alter table presets      enable row level security;
alter table memory_vec   enable row level security;
alter table rate_limits  enable row level security;
alter table usage_daily  enable row level security;
alter table spend_daily  enable row level security;
